modLoader="javafml"
loaderVersion="[37,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/UndeadReturns/issues"

[[mods]]
modId="undeadreturns"
version="${file.jarVersion}"
displayName="Undead Returns"
displayURL="www.curseforge.com/members/melanx/"
authors="MelanX"
description="""
A mod with too much content to describe now. I'm lazy. I hopefully changed this description before releasing it.
"""

[[dependencies.undeadreturns]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.74,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.undeadreturns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.undeadreturns]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1-2.1.3,)"
    ordering="NONE"
    side="BOTH"
